-- =====================================================================
-- 001_schema.sql                                    PostgreSQL 16 (Neon)
-- =====================================================================
-- The whole schema, in its final shape.
--
-- This is NOT a translation of the MySQL 001-008 sequence. Those eight
-- files migrated a database that existed; Neon starts empty, so replaying
-- add-column-then-alter-column archaeology would build the same end state
-- through five pointless ALTERs. The MySQL originals are kept verbatim in
-- ../migrations_mysql_archive/ - they are the history, this is the shape.
--
-- FORWARD ONLY. Once applied anywhere, never edit it. Corrections go in a
-- new numbered migration; the next free number is 003.
--
-- Applied by: psql "$DATABASE_URL" -f 001_schema.sql
-- =====================================================================


-- ---------------------------------------------------------------------
-- users
--
-- email is UNIQUE on lower(email), NOT on email.
--
-- Under MySQL the column collation was utf8mb4_0900_ai_ci, which made every
-- comparison case-insensitive: Devansh@x.com and devansh@x.com were one
-- account, and nothing in the application had to know. Postgres compares
-- text exactly, so the same two strings become two accounts and whoever
-- signed up with a capital letter can no longer log in with a lowercase
-- one. The index below is what keeps that impossible; validators.py
-- lowercases on the way in so the stored value matches what is indexed.
--
-- password_changed_at is TIMESTAMPTZ, and the zone half is load-bearing.
-- auth._session_is_current compares it against a session's time.time(),
-- which is UTC. A naive timestamp read back from a database in a different
-- zone to the web process is silently wrong by the offset between them -
-- which either signs everybody out forever or never signs anybody out.
-- ---------------------------------------------------------------------
CREATE TABLE users (
    user_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name           VARCHAR(100) NOT NULL,
    email               VARCHAR(100) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    contact_number      VARCHAR(15),
    date_of_birth       DATE,
    height_cm           REAL,
    weight_kg           REAL,
    fitness_goal        VARCHAR(20),
    password_changed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_users_email ON users (lower(email));


-- ---------------------------------------------------------------------
-- muscle_groups
--   Reference data. image_path is relative to Frontend/, e.g.
--   assets/muscles/chest.png, so it drops straight into an <img src>.
--
--   Unique on lower(muscle_name) for the same reason as users.email: the
--   seed file relies on the collision to stay re-runnable.
-- ---------------------------------------------------------------------
CREATE TABLE muscle_groups (
    muscle_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muscle_name VARCHAR(50)  NOT NULL,
    image_path  VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX uq_muscle_groups_name ON muscle_groups (lower(muscle_name));


-- ---------------------------------------------------------------------
-- exercises
--   ~2,900 rows: 48 curated, the rest imported from megaGymDataset.csv.
--
-- WHY exercise_name IS COLLATE "C"
--   The catalogue pages by keyset, not OFFSET: "give me the rows after
--   this name" (see exercise_repo._keyset_clause). That comparison and the
--   ORDER BY must agree with the collation of the index backing them, or
--   the seek lands in the wrong place and Load-more silently skips or
--   repeats rows - a bug that shows up as missing exercises, not as an
--   error. Pinning the column to "C" makes every comparison on it byte
--   order, so the index, the ORDER BY and the cursor cannot disagree and
--   no query has to spell out a COLLATE clause.
--
--   The cost is that uppercase sorts before lowercase. Harmless here:
--   import_exercises.title_case() normalises every name to leading caps
--   before it is ever written.
--
--   The UNIQUE index is on lower(exercise_name) rather than the column,
--   which is what makes the importer's case-insensitive dedup agree with
--   what the database actually enforces.
-- ---------------------------------------------------------------------
CREATE TABLE exercises (
    exercise_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_name    VARCHAR(100) COLLATE "C" NOT NULL,
    muscle_id        INTEGER NOT NULL
                     REFERENCES muscle_groups(muscle_id) ON DELETE RESTRICT,
    equipment        VARCHAR(50),
    description      TEXT,
    exercise_type    VARCHAR(30),
    difficulty_level VARCHAR(20),
    rating           NUMERIC(3,2)
);

CREATE UNIQUE INDEX uq_exercises_name_muscle
    ON exercises (lower(exercise_name), muscle_id);

-- sort=name: ORDER BY exercise_name, muscle_id, seeked into by the cursor.
CREATE INDEX idx_exercises_name_muscle ON exercises (exercise_name, muscle_id);

-- sort=muscle: ORDER BY muscle_id, exercise_name. Also the index for the
-- foreign key - Postgres, unlike InnoDB, does not create one for you, so
-- without this every join from workout_sets and every muscle filter is a
-- sequential scan of the whole catalogue.
CREATE INDEX idx_exercises_muscle_name ON exercises (muscle_id, exercise_name);

CREATE INDEX idx_exercises_equipment ON exercises (equipment);


-- ---------------------------------------------------------------------
-- workouts
--   One row per user per training day - a container, holding no training
--   data of its own.
--
--   UNIQUE (user_id, workout_date) is what workout_repo.log_set upserts
--   against. Without it a double-submit creates two workout rows for one
--   date and splits a day's training in two. It also serves as the index
--   for the foreign key, and Postgres reads it backwards for the
--   ORDER BY workout_date DESC in stats_repo.
--
--   ON DELETE RESTRICT, deliberately: no code path may cascade a training
--   history away by accident. Destroying one is user_repo.delete_account's
--   job and nowhere else's.
-- ---------------------------------------------------------------------
CREATE TABLE workouts (
    workout_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    workout_date DATE NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_workouts_user_date UNIQUE (user_id, workout_date)
);


-- ---------------------------------------------------------------------
-- workout_sets
--   One row per set performed. The actual training data.
--
--   time_under_tension is no longer written - the input was removed from
--   the form - but the column and its history stay. Removing a feature is
--   not a reason to destroy the data behind it.
--
--   reps and set_order are SMALLINT with a CHECK rather than MySQL's
--   SMALLINT UNSIGNED, which has no Postgres equivalent. The CHECK is what
--   actually enforced the floor anyway; UNSIGNED only moved the ceiling.
-- ---------------------------------------------------------------------
CREATE TABLE workout_sets (
    set_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id         INTEGER NOT NULL
                       REFERENCES workouts(workout_id) ON DELETE CASCADE,
    exercise_id        INTEGER NOT NULL
                       REFERENCES exercises(exercise_id) ON DELETE RESTRICT,
    weight             NUMERIC(6,2),
    reps               SMALLINT,
    time_under_tension INTEGER,
    comments           VARCHAR(500),
    set_order          SMALLINT,
    created_at         TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT chk_workout_sets_reps      CHECK (reps > 0),
    CONSTRAINT chk_workout_sets_set_order CHECK (set_order > 0)
);

-- Serves four things at once: the foreign key, the join from workouts, the
-- ORDER BY set_order, and the MAX(set_order) lookup that assigns the next
-- one. One index, not four.
CREATE INDEX idx_workout_sets_workout ON workout_sets (workout_id, set_order);

CREATE INDEX idx_workout_sets_exercise ON workout_sets (exercise_id);


-- ---------------------------------------------------------------------
-- weight_logs
--   Bodyweight over time. users.weight_kg holds only the current value and
--   is overwritten, so it cannot answer "am I trending up or down".
--
--   UNIQUE (user_id, logged_on): one reading per person per day, so a
--   second entry corrects the first rather than stacking. Also the index
--   for the foreign key.
-- ---------------------------------------------------------------------
CREATE TABLE weight_logs (
    log_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    logged_on  DATE NOT NULL,
    weight_kg  NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_weight_logs_user_day UNIQUE (user_id, logged_on)
);


-- ---------------------------------------------------------------------
-- personal_records
--   Best effort per user per exercise.
--
--   A DERIVED CACHE, not a source of truth. It must always be rebuildable
--   from workout_sets - see queries/scratch.sql. If it ever disagrees with
--   the sets, the sets win.
--
--   updated_at has no ON UPDATE CURRENT_TIMESTAMP equivalent in Postgres.
--   Rather than add a trigger for a column nothing reads back, the two
--   writers in workout_repo set it explicitly. If a third writer ever
--   appears and forgets, the value goes stale - that is the trade, and it
--   is cheaper than a trigger nobody remembers exists.
-- ---------------------------------------------------------------------
CREATE TABLE personal_records (
    pr_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    exercise_id   INTEGER NOT NULL
                  REFERENCES exercises(exercise_id) ON DELETE RESTRICT,
    best_weight   NUMERIC(6,2) NOT NULL,
    best_reps     SMALLINT NOT NULL,
    estimated_1rm NUMERIC(6,2) NOT NULL,
    achieved_on   DATE NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_personal_records_user_exercise UNIQUE (user_id, exercise_id),
    CONSTRAINT chk_personal_records_best_reps CHECK (best_reps > 0)
);

CREATE INDEX idx_personal_records_exercise ON personal_records (exercise_id);


-- ---------------------------------------------------------------------
-- password_reset_tokens
--   token_hash is the hex SHA-256 of the token that was emailed. The raw
--   token is never stored, so a dump of this table yields nothing that can
--   be put in a URL.
--
--   VARCHAR(64), not CHAR(64): Postgres blank-pads CHAR, and the value is
--   compared with hmac.compare_digest against an unpadded hex string.
--   64 characters always fill it exactly, so nothing is lost and one way
--   to be surprised is removed.
--
--   Not UNIQUE on token_hash: a collision is impossible in practice, and a
--   UNIQUE constraint would turn that impossibility into a 500 on a
--   password reset rather than something the application can reason about.
--
--   The (user_id) index serves both the "spend this user's other unused
--   tokens" path and the cascade when an account is deleted. A partial
--   index on used_at IS NULL was considered and dropped: the rate limit
--   caps a user at 3 tokens an hour, so there is never enough of a row
--   count for the extra selectivity to be worth a second index to maintain.
-- ---------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
    token_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash   VARCHAR(64) NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    used_at      TIMESTAMPTZ,
    requested_ip VARCHAR(45),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The hot path: one seek from a link click.
CREATE INDEX idx_reset_tokens_hash ON password_reset_tokens (token_hash);

CREATE INDEX idx_reset_tokens_user ON password_reset_tokens (user_id);
